Starting test 1
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 1 exceeded maximum allowed time of 30
Finished test 1
Test 1:		FAILED
Starting test 2
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 2 exceeded maximum allowed time of 30
Finished test 2
Test 2:		FAILED
Starting test 3
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 3 exceeded maximum allowed time of 30
Finished test 3
Test 3:		FAILED
Starting test 4
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 4 exceeded maximum allowed time of 30
Finished test 4
Test 4:		FAILED
Starting test 5
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 5 exceeded maximum allowed time of 30
Finished test 5
Test 5:		FAILED
Starting test 6
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 6 exceeded maximum allowed time of 30
Finished test 6
Test 6:		FAILED
Starting test 7
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 7 exceeded maximum allowed time of 30
Finished test 7
Test 7:		FAILED
Starting test 8
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 8 exceeded maximum allowed time of 30
Finished test 8
Test 8:		FAILED
Starting test 9
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 9 exceeded maximum allowed time of 60
Finished test 9
Test 9:		FAILED
Starting test 10
Traceback (most recent call last):
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "C:\Users\Alexandra\Desktop\3sem2\ASC\tema1\asc-public\assignments\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 10 exceeded maximum allowed time of 60
Finished test 10
Test 10:		FAILED

Run pylint

C:\Users\Alexandra\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: No module named pylint
